import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

import Providers from "@/app/providers";
// These styles apply to every route in the application
import "./globals.css";
//
//    components (this needs to be ahead in the front of the NPM packages for this file)
import HanekawaNavbar from "@/components/ui/hanekawaNavbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={inter.className}>
                <Providers>
                    <HanekawaNavbar />
                    <main>{children}</main>
                </Providers>
            </body>
        </html>
    );
}
